<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE familie [
        <!ELEMENT familie ANY>
        <!ELEMENT vader (voornaam, achternaam)>
        <!ELEMENT moeder (voornaam, achternaam)>
        <!ELEMENT kinderen (kind+)>
        <!ELEMENT kind (voornaam, achternaam)>
        <!ELEMENT voornaam (#PCDATA)>
        <!ELEMENT achternaam (#PCDATA)>
        <!ENTITY achternaam "Vermeulen">
        ]>

<familie>
    <vader>
        <voornaam>Jos</voornaam>
        <achternaam>&achternaam;</achternaam>
    </vader>
    <moeder>
        <voornaam>Marie</voornaam>
        <achternaam>&achternaam;</achternaam>
    </moeder>
    <kinderen>
        <kind>
            <voornaam>Joske</voornaam>
            <achternaam>&achternaam;</achternaam>
        </kind>
        <kind>
            <voornaam>Marieke</voornaam>
            <achternaam>&achternaam;</achternaam>
        </kind>
    </kinderen>
</familie>